language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script: PYTHONPATH=. coverage run `which django-admin` test --settings=test_settings
after_success:
  coveralls
