# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='version',
            field=models.CharField(max_length=64),
        ),
    ]
